var reasons = [
    "my dog got sick and now I've got to comfort her",
    "i have a super important work project coming up in 3 months",
    "i overate on falafel last night",
	"my shoes got stolen and now i don't have any",
	"the street in front of my house is flooding",
	"there's a bear in front of my apartment",
	"my mom's visiting and she doesn't let me stay out late",
	"i've got an ant in the kitchen and i've gotta get rid of it",
	"i'm waiting for an amazon package to arrive",
	"my hairdresser said i can't go outside for a day",
	"my doctor said the outside air is bad for me",
	"i've got to help my brother set up the new TV",
	"there are no ubers in my neighborhood at all",
	"i'm working on australian timezone today",
	"i've got a soccer game later and i have to rest up",
	"the new house of cards season is coming out today",
	"my neighbours are napping and i don't want to wake them up with the door",
	"my cat gets lonely and i couldn't find a catsitter",
	"i just made coffee and it'll get cold",
	"i need to water my plants every 2 hours",
	"it's leg day so i need to rest my legs",
	"i had a houseparty last night and now i've got to clean up",
	"it's kinda hot outside today",
	"my ducks are all over the place, i've got to get them in a row",
	"i can't find my phone and i can't leave without it",
	"i'm practicing my TED talk in case they invite me to speak",
	"i'm running an experiment involving a hot bath and 58 rubber ducks"
]

